"""add subscription tier to users

Revision ID: 7c76f52ecbfc
Revises: 8593bee96dcf
Create Date: 2025-10-01 20:30:38.522558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c76f52ecbfc'
down_revision = '8593bee96dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=20), nullable=False, server_default='pro'))    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###